# Generated by Django 6.0.2 on 2026-02-12 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='comleted',
            new_name='competed',
        ),
    ]
