# Generated by Django 6.0.2 on 2026-02-20 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_remove_registeruser_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisterUser',
        ),
    ]
