# Generated by Django 6.0.2 on 2026-02-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0006_delete_registeruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Todo', 'Todo'), ('Complete', 'Complete'), ('In Progress', 'In Progress')], default='Todo', max_length=20),
        ),
    ]
