# Generated by Django 6.0.2 on 2026-02-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0007_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('Complete', 'Complete'), ('In Progress', 'In Progress')], default='pending', max_length=20),
        ),
    ]
