# Generated by Django 6.0.2 on 2026-02-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0008_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Complete', 'Complete'), ('In Progress', 'In Progress')], default='Pending', max_length=20),
        ),
    ]
